updates

diff --git a/.github/workflows/initializeEcrAppRunner.yml b/.github/workflows/initializeEcrAppRunner.yml
--- a/.github/workflows/initializeEcrAppRunner.yml
+++ b/.github/workflows/initializeEcrAppRunner.yml
@@ -18,14 +18,26 @@ jobs:
       id: assume-role
       run: |
         ROLE_ARN="arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/opera-erc-apprunner-role"
-        SESSION_NAME="opera-erc-apprunner-session"
+        SESSION_NAME="${{ github.workflow }}-${{ github.run_id }}-${{ github.actor }}"
+
+        echo "Assuming role with ARN: $ROLE_ARN and session name: $SESSION_NAME"
         
-        CREDENTIALS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name $SESSION_NAME)
+        CREDENTIALS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name $SESSION_NAME --output json)
         
-        echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
-        echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
-        echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV
-    
+        if [ $? -ne 0 ]; then
+        echo "Failed to assume role"
+        exit 1
+        fi
+
+        echo "Successfully assumed role"
+        
+        export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')
+        export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')
+        export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')
+
+        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
+        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
+        echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"    
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
 
